# .github/actions/get-latest-release-version/action.yml
name: 'Get Latest Release Version'
description: 'Get the latest release version with an optional default'
inputs:
  defaultVersion:
    description: 'Default version if no release is found'
    required: false
    default: '0.1'
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set Output
      id: get_version
      run: |
        LATEST_VERSION=$(gh release list | head -n 1 | awk '{print $1}') || true
        if [ -z "$LATEST_VERSION" ]; then
          LATEST_VERSION="${{ inputs.defaultVersion }}"
        fi
        echo "version=$LATEST_VERSION" >> $GITHUB_ENV
      shell: bash
