# .github/actions/get-latest-release-version/action.yml
name: 'Get Latest Release Version'
description: 'Get the latest release version with an optional default'
inputs:
  defaultVersion:
    description: 'Default version if no release is found'
    required: false
    default: '0.1'

outputs:
  version:
    description: 'Latest Release Version'
    value: ${{ env.GITHUB_ENV.version }}

runs:
  using: "composite"
  steps:
    - name: Get Latest Release Version tag or default
      run: |
        LATEST_VERSION=$(gh release list | head -n 1 | awk '{print $1}') || true
        if [ -z "$LATEST_VERSION" ]; then
          LATEST_VERSION="${{ inputs.defaultVersion }}"
        fi
        echo "version=$LATEST_VERSION" >> $GITHUB_ENV
      shell: bash
