# .github/actions/attach-to-release/action.yml
name: 'Publish to GitHub Release'
description: 'Attach artifacts to a GitHub release'
inputs:
    token:
        description: 'GitHub Token'
        required: true
    globPattern:
        description: 'File path of artifacts'
        required: true
    releaseId:
        description: 'Release ID'
        required: true
        
runs:
    using: "composite"
    steps:
        -   name: Upload to GitHub Release
            uses: xresloader/upload-to-github-release@v1
            with:
                file: ${{ inputs.globPattern }}
                release_id: ${{ inputs.releaseId }}
                overwrite: false
                verbose: true
            env:
                GITHUB_TOKEN: ${{ inputs.token }}
            working-directory: defaults.run.working-directory
