# .github/actions/dotnet-nuget-cd/action.yml
name: '.NET NuGet Continuous Delivery (pack and publish)'
description: 'Package and publish a .NET project to NuGet.org'

inputs:
    configuration:
        description: 'Build configuration (Release/Debug)'
        required: false
        default: 'Release'
    
    outputDirectory:
        description: 'Output directory for NuGet package'
        required: false
        default: 'nupkgs'
    
    nugetKey:
        description: 'NuGet API Key'
        required: true
    
    packageVersion:
        description: 'Package version'
        required: true

runs:
    using: "composite"
    steps:
        -   name: Pack Project
            uses: frankhaugen/Workflows/.github/actions/dotnet-pack@main
            with:
                configuration: ${{ inputs.configuration }}
                outputDirectory: ${{ inputs.outputDirectory }}
                dotnetVersion: ${{ inputs.dotnetVersion }}
                packageVersion: ${{ inputs.packageVersion }}
        -   name: Publish to NuGet.org
            uses: frankhaugen/Workflows/.github/actions/publish-nuget@main
            with:
                nugetKey: ${{ inputs.nugetKey }}
                globPattern: '**/*.nupkg'