# .github/actions/dotnet-setup/action.yml
name: 'Setup .NET'
description: 'Setup .NET environment'
inputs:
    dotnetVersion:
        description: '.NET SDK version'
        required: false
        default: '8.0.x'
runs:
    using: "composite"
    steps:
        - name: Setup .NET Core SDK (${{ inputs.dotnetVersion }})
          uses: actions/setup-dotnet@v3
          with:
              dotnet-version: ${{ inputs.dotnetVersion }}
