# .github/actions/dotnet-setup/action.yml
name: 'Setup .NET'
description: 'Setup .NET environment'
inputs:
    dotnetVersion:
        description: '.NET SDK version'
        required: false
        default: '8.0.x'
runs:
    using: "composite"
    steps:
        - name: Check if required .NET Core SDK version is already installed
          id: check_dotnet
          shell: bash
          run: |
              REQUIRED_VERSION=${{ inputs.dotnetVersion }}
              INSTALLED_VERSION=$(dotnet --version 2>/dev/null || echo "none")
              if [[ "$INSTALLED_VERSION" == "$REQUIRED_VERSION" ]]; then
                echo "already_installed=true" >> $GITHUB_ENV
              else
                echo "already_installed=false" >> $GITHUB_ENV
              fi

        - name: Setup .NET Core SDK (${{ inputs.dotnetVersion }})
          if: env.already_installed == 'false'
          uses: actions/setup-dotnet@v3
          with:
              dotnet-version: ${{ inputs.dotnetVersion }}
        