# .github/actions/dotnet-ci/action.yml

name: 'DotNet CI'
description: 'Continuous Integration for .NET projects, builds and tests'

inputs:
  configuration:
    description: 'Configuration to build'
    required: false
    default: 'Release'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: ./.github/actions/checkout-repo
    - name: Prepare Versions
      id: get_release_version
      uses: ./.github/actions/get-latest-release-version
    - name: Setup .NET
      uses: ./.github/actions/dotnet-setup
    - name: Build and Test
      uses: ./.github/actions/dotnet-build-test
      with:
        configuration: ${{ inputs.configuration }}
        assemblyVersion: ${{ steps.get_release_version.outputs.version }}
#        assemblyVersion: ${{ env.GITHUB_ENV.version }}