# .github/actions/dotnet-ci/action.yml

name: 'DotNet CI'
description: 'Continuous Integration for .NET projects, builds and tests'

inputs:
    configuration:
        description: 'Configuration to build'
        required: false
        default: 'Release'
    assemblyVersion:
        description: 'Assembly version'
        required: true
    dotnetVersion:
        description: '.NET SDK version'
        required: false
        default: '8.0.x'

runs:
    using: "composite"
    steps:
        -   name: Checkout
            uses: frankhaugen/Workflows/.github/actions/checkout-repo@main
        -   name: Setup .NET
            uses: frankhaugen/Workflows/.github/actions/dotnet-setup@main
        -   name: Build and Test
            uses: frankhaugen/Workflows/.github/actions/dotnet-build-test@main
            with:
                configuration: ${{ inputs.configuration }}
                assemblyVersion: ${{ inputs.assemblyVersion }}
                dotnetVersion: ${{ inputs.dotnetVersion }}
