# .github/actions/dotnet-pack/action.yml
name: 'Package .NET Project'
description: 'Package a .NET project into a NuGet package'
inputs:
    configuration:
        description: 'Build configuration (Release/Debug)'
        required: false
        default: 'Release'
    outputDirectory:
        description: 'Output directory for NuGet package'
        required: false
        default: 'nupkgs'
    packageVersion:
        description: 'Package version'
        required: true

runs:
    using: "composite"
    steps:
        -   name: Pack Project
            run: dotnet pack --configuration ${{ inputs.configuration }} --no-build --output ${{ inputs.outputDirectory }} /p:Version=${{ inputs.packageVersion }}
            shell: bash
            working-directory: ${{defaults.run.working-directory}}