# .github/actions/dotnet-build/action.yml
name: 'Build .NET Project'
description: 'Build a .NET project with specified parameters'
inputs:
    configuration:
        description: 'Build configuration (Release/Debug)'
        required: false
        default: 'Release'
    assemblyVersion:
        description: 'Assembly version'
        required: false
        default: '0.1'
    dotnetVersion:
        description: '.NET SDK version'
        required: false
        default: '8.0.x'
runs:
    using: "composite"
    steps:
        -   name: Setup .NET Core (${{ inputs.dotnetVersion }})
            uses: frankhaugen/Workflows/.github/actions/dotnet-setup@main
            with:
                dotnetVersion: ${{ inputs.dotnetVersion }}
        -   name: Build Project
            run: dotnet build --configuration ${{ inputs.configuration }} /p:Version=${{ inputs.assemblyVersion }} -verbosity:detailed
            shell: bash
            working-directory: defaults.run.working-directory
