# .github/actions/publish-github-packages/action.yml
name: 'Publish to GitHub Packages'
description: 'Publish package to GitHub Packages'
inputs:
    username:
        description: 'GitHub Username'
        required: true
    token:
        description: 'GitHub Token'
        required: true
    globPattern:
        description: 'Glob pattern to find files to publish'
        required: true
runs:
    using: "composite"
    steps:
        -   run: dotnet nuget add source --username ${{ inputs.username }} --password ${{ inputs.token }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ inputs.username }}/index.json"
            shell: bash
            working-directory: defaults.run.working-directory
        -   run: dotnet nuget push "${{ inputs.globPattern }}" --source "github" --api-key ${{ inputs.token }} --skip-duplicate
            shell: bash
            working-directory: defaults.run.working-directory
