name: 'Run a C# Script'
description: 'Runs a C# script with .NET and NuGet package support using dotnet-script'
inputs:
    script-path:
        description: 'Path to the C# script file'
        required: true
        
runs:
    using: "composite"
    steps:
        -   name: Run script
            run: dotnet script ${{ inputs.script-path }}
            shell: bash
