name: 'Run dotnet-script'
description: 'Runs a C#/dotnet script with .NET and NuGet package support using dotnet-script'
inputs:
    script-path:
        description: 'Path to the C# script file'
        required: true
        
runs:
    using: "composite"
    steps:
        -   name: Run script
            run: dotnet script ${{ inputs.script-path }}
            shell: bash
            working-directory: defaults.run.working-directory
