# .github/actions/dotnet-test/action.yml
name: 'Run .NET Tests'
description: 'Run .NET tests with configurable settings'
inputs:
    configuration:
        description: 'Build configuration (Release/Debug)'
        required: false
        default: 'Release'
    dotnetVersion:
        description: '.NET SDK version'
        required: false
        default: '8.0.x'
    timeout:
        description: 'Test timeout in minutes'
        required: false
        default: '10'
    continueOnError:
        description: 'Continue on error'
        required: false
        default: 'false'
runs:
    using: "composite"
    steps:
        -   name: Setup .NET Core (${{ inputs.dotnetVersion }})
            uses: frankhaugen/Workflows/.github/actions/dotnet-setup@main
            with:
                dotnetVersion: ${{ inputs.dotnetVersion }}
        -   name: Run Tests
            run: dotnet test --configuration ${{ inputs.configuration }} --no-build --timeout ${{ inputs.timeout }}m
            continue-on-error: ${{ inputs.continueOnError }}
            shell: bash
