# .github/actions/dotnet-test/action.yml
name: 'Run .NET Tests'
description: 'Run .NET tests with configurable settings'
inputs:
    configuration:
        description: 'Build configuration (Release/Debug)'
        required: false
        default: 'Release'
runs:
    using: "composite"
    steps:
        -   name: Run Tests
            run: dotnet test --configuration ${{ inputs.configuration }} --no-build
            shell: bash
            working-directory: ${{defaults.run.working-directory}}
