name: Pull Request Workflow for nugets (Ubuntu)

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating system to run the workflow on'
        required: true
        default: 'ubuntu-latest'
        type: string
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system to run the workflow on'
        required: true
        default: 'ubuntu-latest'
        type: string

jobs:
  pull_request:
    name: Pull Request Job
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: frankhaugen/Workflows/.github/actions/github-checkout@main
      - uses: frankhaugen/Workflows/.github/actions/dotnet-setup@main
      - name: Run .NET Build Action
        uses: frankhaugen/Workflows/.github/actions/dotnet-build@main
        with:
          assemblyVersion: 0.0.1
          configuration: Release
      - name: Run .NET Test Action
        uses: frankhaugen/Workflows/.github/actions/dotnet-test@main
        with:
          configuration: Release