name: Get Version Workflow for nugets (Ubuntu)

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      ReleaseVersion:
        description: "The version string for the release"
        value: ${{ jobs.get_version.outputs.ReleaseVersion }}
      PreviewAssemblyVersion:
        description: "The version string for the preview assembly"
        value: ${{ jobs.get_version.outputs.PreviewAssemblyVersion }}
      PreviewPackageVersion:
        description: "The version string for the preview package"
        value: ${{ jobs.get_version.outputs.PreviewPackageVersion }}

jobs:
  get_version:
    name: Get Version Strings
    runs-on: ubuntu-latest
    outputs:
      ReleaseVersion: ${{ steps.get_release_version.outputs.release_version }}
      PreviewAssemblyVersion: ${{ steps.get_preview_assembly_version.outputs.preview_assembly_version }}
      PreviewPackageVersion: ${{ steps.get_preview_package_version.outputs.preview_package_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Find Latest Tag
        id: version
        uses: oprypin/find-latest-tag@v1.0.4
        with:
          repository: ${{ github.repository }}
          releases-only: true
        
      - name: Get Release Version
        id: get_release_version 
        run: echo "release_version=${{ steps.version.outputs.tag }}.${{ github.run_number }}" >> $GITHUB_STATE
      
      - name: Get Preview Assembly Version
        id: get_preview_assembly_version
        run: echo "preview_assembly_version=${{ steps.version.outputs.tag }}.${{ github.run_number }}" >> $GITHUB_STATE

      - name: Get Preview Package Version
        id: get_preview_package_version
        run: echo "preview_package_version=${{ steps.version.outputs.tag }}.${{ github.run_number }}-preview" >> $GITHUB_STATE
