name: Publish Preview Workflow for nugets (Ubuntu)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_pack_publish_preview:
    name: Publish Preview Job
    runs-on: ubuntu-latest
    steps:
      - uses: frankhaugen/Workflows/.github/actions/github-checkout@main
      - uses: frankhaugen/Workflows/.github/actions/dotnet-setup@main
      - name: Get latest release
        id: get_release
        uses: frankhaugen/Workflows/.github/actions/github-latest-release@main
        with:
          token: ${{ github.token }}
      - name: Run .NET Build Action
        uses: frankhaugen/Workflows/.github/actions/dotnet-build@main
        with:
          assemblyVersion: ${{ steps.get_release.outputs.tag }}.${{ github.run_number }}
          configuration: Release
      - name: Run .NET Test Action
        uses: frankhaugen/Workflows/.github/actions/dotnet-test@main
        continue-on-error: true
        with: 
          configuration: Release
      - name: Run .NET Pack Action
        uses: frankhaugen/Workflows/.github/actions/dotnet-pack@main
        with:
          configuration: Release
          outputDirectory: nupkgs
          packageVersion: ${{ steps.get_release.outputs.tag }}.${{ github.run_number }}-preview
      - name: Publish to NuGet.org
        uses: frankhaugen/Workflows/.github/actions/publish-nuget@main
        with:
          nugetKey: ${{ secrets.nugetKey }}
          globPattern: '**/*.nupkg'