name: Pull Request Workflow for nugets (Ubuntu)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pull_request:
    name: Pull Request Job
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test
        uses: frankhaugen/Workflows/.github/actions/dotnet-ci@main
        with:
          configuration: Release
          assemblyVersion: '0.0.1'