name: Publish Preview Workflow for nugets (Ubuntu)

on:
  workflow_call:
    inputs:
      ReleaseVersion:
        type: string
      PreviewAssemblyVersion:
        type: string
      PreviewPackageVersion:
        type: string
  workflow_dispatch:
    inputs:
      ReleaseVersion:
        description: 'Release Version'
        required: true
      PreviewAssemblyVersion:
        description: 'Preview Assembly Version'
        required: true
      PreviewPackageVersion:
        description: 'Preview Package Version'
        required: true

jobs:
  build_pack_publish_preview:
    name: Merge Job
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Build (${{ PreviewAssemblyVersion }})
        run: dotnet build --configuration Release /p:Version=${{ PreviewAssemblyVersion }}
      - name: Test
        run: dotnet test --configuration Release --no-build
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output nupkgs /p:Version=${{ PreviewPackageVersion }}
      - name: Publish NuGet
        run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json --skip-duplicate