name: Pull Request Workflow for nugets (Ubuntu)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pull_request:
    name: Pull Request Job
    runs-on: ubuntu-latest
    steps:
      - uses: frankhaugen/Workflows/.github/actions/github-checkout@main
      - uses: frankhaugen/Workflows/.github/actions/dotnet-setup@main
      - name: Build
        uses: frankhaugen/Workflows/.github/actions/dotnet-build@main
        with:
          assemblyVersion: 0.0.1
          configuration: Release
      - name: Test
        uses: frankhaugen/Workflows/.github/actions/dotnet-test@main
        with:
          configuration: Release