name: Release Workflow for nugets (Ubuntu)

on:
  workflow_call:
    inputs:
      ReleaseVersion:
        type: string
        required: true
      PreviewAssemblyVersion:
        type: string
        required: true
      PreviewPackageVersion:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      ReleaseVersion:
        description: 'Release Version'
        required: true
      PreviewAssemblyVersion:
        description: 'Preview Assembly Version'
        required: true
      PreviewPackageVersion:
        description: 'Preview Package Version'
        required: true
  
jobs:
  build_pack_publish_release:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Build (${{ inputs.ReleaseVersion }})
        run: dotnet build --configuration Release /p:Version=${{ inputs.ReleaseVersion }}
      - name: Test
        run: dotnet test --configuration Release --no-build
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output nupkgs /p:Version=${{ inputs.ReleaseVersion }}
      - name: Publish NuGet
        run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json --skip-duplicate
        
      - name: Set GitHub Package Source
        continue-on-error: true
        run : dotnet nuget add source --username frankhaugen --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/frankhaugen/index.json"        
      - name: Push NuGet Package to GitHub
        continue-on-error: true
        run: dotnet nuget push "**/*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Attach artifiacts to release
        uses: xresloader/upload-to-github-release@main
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "nupkgs/*.nupkg"
          release_id: ${{ steps.get_current_release.outputs..id }}
          overwrite: false
          verbose: true
