name: Release Workflow for nugets (Ubuntu)

on:
  workflow_call:
  workflow_dispatch:
    
jobs:
  build_pack_publish_release:
    name: Release Job    
    runs-on: ubuntu-latest
    steps:
      - name: Get version from latest release
        id: get_version
        uses: ./.github/actions/github-latest-release-version
      - name: Run .NET CI Action
        uses: ./.github/actions/dotnet-ci
        with:
          assemblyVersion: ${{ steps.get_version.outputs.version }}
      - name: Pack
        uses: ./.github/actions/dotnet-pack
        with:
          dotnetVersion: 8.0.x
          configuration: Release
          outputDirectory: nupkgs
          packageVersion: ${{ steps.get_version.outputs.version }}
      - name: Publish
        uses: ./.github/actions/publish-repo
        with:
          attachToRelease: true
          publishToGitHubPackages: true
          publishToNuGet: true
          globPattern: '**/*.nupkg'
          nugetKey: ${{ secrets.NugetKey }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}