name: Pull Request Workflow for nugets (Ubuntu)

on:
  workflow_call:
    secrets: inherit
  workflow_dispatch:
    secrets: inherit

jobs:
  pull_request:
    name: Pull Request Job
    runs-on: ubuntu-latest
    steps:
      - name: Build and Test
        uses: ./.github/actions/dotnet-ci
        with:
          configuration: Release
          assemblyVersion: '0.0.1'