# .github/actions/attach-to-release/action.yml
name: 'Attach to GitHub Release'
description: 'Attach artifacts to a GitHub release'
inputs:
  token:
    description: 'GitHub Token'
    required: true
  releaseId:
    description: 'Release ID'
    required: true
  filePath:
    description: 'File path of artifacts'
    required: true
runs:
  using: "composite"
  steps:
    - uses: xresloader/upload-to-github-release@main
      with:
        file: ${{ inputs.filePath }}
        release_id: ${{ inputs.releaseId }}
        overwrite: false
        verbose: true
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
